import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1724436207337 implements MigrationInterface {
    name = 'Migrations1724436207337'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`photos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`mimeType\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`personal-info\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NOT NULL, \`firstName\` varchar(255) NULL, \`lastName\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`address\` varchar(255) NULL, \`dob\` date NULL, \`gender\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`profilePictureId\` int NULL, UNIQUE INDEX \`IDX_93b09314f05ed2653da12beabe\` (\`email\`), UNIQUE INDEX \`REL_98ca4ec426318eb638694d4f54\` (\`profilePictureId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`password\` varchar(255) NOT NULL, \`role\` int NOT NULL DEFAULT '1', \`notificationToken\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`personalInfoId\` int NULL, UNIQUE INDEX \`REL_533b61ed333a730035da8c1055\` (\`personalInfoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`space-units\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`status\` smallint NOT NULL DEFAULT '1', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`spaceId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`spaces\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stores\` (\`id\` int NOT NULL AUTO_INCREMENT, \`description\` text NOT NULL, \`type\` int NOT NULL DEFAULT '1', \`passCode\` varchar(255) NOT NULL, \`paymentDate\` int NOT NULL DEFAULT '1', \`hotline\` varchar(255) NULL, \`facebookUrl\` varchar(255) NULL, \`tiktokUrl\` varchar(255) NULL, \`youtubeUrl\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`logoPictureId\` int NULL, UNIQUE INDEX \`REL_8268c3cb6bc33b77580220bcdc\` (\`logoPictureId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`spends\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`amount\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`price\` int NOT NULL DEFAULT '0', \`unit\` varchar(255) NOT NULL, \`duration\` int NULL, \`barcode\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`imageId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_e8c788030f2c88cbccf6965328\` (\`imageId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`combo-quantity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`comboId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`combos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`price\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`imageId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_22113bc933266b8b87f291a9a7\` (\`imageId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promo-codes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`discount\` int NOT NULL, \`total\` int NULL, \`timeStart\` datetime NULL, \`timeEnd\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receiptProducts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`price\` int NOT NULL, \`priceDiscount\` int NOT NULL, \`promoDiscount\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`receiptId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`member-ranks\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NULL, \`discount\` tinyint NULL DEFAULT '0', \`condition\` tinyint NULL DEFAULT '0', \`requirement1\` int NULL DEFAULT '0', \`requirement2\` int NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`joinedDate\` date NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`personalInfoId\` int NULL, \`rankId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_50976ab09a67603d04656554e2\` (\`personalInfoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receipts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`subTotal\` int NOT NULL, \`total\` int NOT NULL, \`memberDiscount\` int NULL, \`extraDiscount\` int NULL, \`promoDiscount\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, \`customerId\` int NULL, \`spaceUnitId\` int NULL, UNIQUE INDEX \`REL_2965a0ed54a06bcb4f6c8d1a32\` (\`spaceUnitId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` varchar(255) NOT NULL, \`url\` varchar(255) NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`isSendMail\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employee-info\` (\`id\` int NOT NULL AUTO_INCREMENT, \`isVerified\` tinyint NOT NULL DEFAULT 0, \`isActive\` tinyint NOT NULL DEFAULT 0, \`joinedDate\` date NULL, \`dayOffPerMonth\` int NULL DEFAULT '0', \`salary\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`identityCardImage1Id\` int NULL, \`identityCardImage2Id\` int NULL, \`personalInfoId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_eb4181527b71aa76bef4f2dc59\` (\`identityCardImage1Id\`), UNIQUE INDEX \`REL_4cc978dbd3c0b4fe114bc1ab27\` (\`identityCardImage2Id\`), UNIQUE INDEX \`REL_e2497a12faa9628c41bfdbaf98\` (\`personalInfoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`configs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`value\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`combo-trackings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantityUsed\` int NOT NULL, \`remaining\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`comboId\` int NULL, \`customerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`space-units_merged_unit_space-units\` (\`spaceUnitsId_1\` int NOT NULL, \`spaceUnitsId_2\` int NOT NULL, INDEX \`IDX_bb84f8edd17b8e275e6686021f\` (\`spaceUnitsId_1\`), INDEX \`IDX_2a236211c5f4925ec5e7b2bf94\` (\`spaceUnitsId_2\`), PRIMARY KEY (\`spaceUnitsId_1\`, \`spaceUnitsId_2\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receipt_products_promo_codes_promo-codes\` (\`receiptProductsId\` int NOT NULL, \`promoCodesId\` int NOT NULL, INDEX \`IDX_7e49ca7b593d039c39fe37e760\` (\`receiptProductsId\`), INDEX \`IDX_bc195120a6e5ac1a8741cb25d8\` (\`promoCodesId\`), PRIMARY KEY (\`receiptProductsId\`, \`promoCodesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receipts_promo_codes_promo-codes\` (\`receiptsId\` int NOT NULL, \`promoCodesId\` int NOT NULL, INDEX \`IDX_8812c885c4168496babaf03a59\` (\`receiptsId\`), INDEX \`IDX_ec4625350a66c8727f6d6dfef4\` (\`promoCodesId\`), PRIMARY KEY (\`receiptsId\`, \`promoCodesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`photos\` ADD CONSTRAINT \`FK_b8d4271e04660159c5f6fabfc9c\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`personal-info\` ADD CONSTRAINT \`FK_98ca4ec426318eb638694d4f542\` FOREIGN KEY (\`profilePictureId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_533b61ed333a730035da8c1055d\` FOREIGN KEY (\`personalInfoId\`) REFERENCES \`personal-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`space-units\` ADD CONSTRAINT \`FK_ec10b62ba8854176bf8a386cd1a\` FOREIGN KEY (\`spaceId\`) REFERENCES \`spaces\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spaces\` ADD CONSTRAINT \`FK_86ece25c1dfe489bf748da779e6\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stores\` ADD CONSTRAINT \`FK_f36d697e265ed99b80cae6984c9\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stores\` ADD CONSTRAINT \`FK_8268c3cb6bc33b77580220bcdc8\` FOREIGN KEY (\`logoPictureId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spends\` ADD CONSTRAINT \`FK_ce454cf10e9405c811a26b6e55d\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_e8c788030f2c88cbccf6965328c\` FOREIGN KEY (\`imageId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_782da5e50e94b763eb63225d69d\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` ADD CONSTRAINT \`FK_2841db6ff5a6d835770decb23d6\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` ADD CONSTRAINT \`FK_d3a7e5e3ec3de49cdb1a156a667\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combos\` ADD CONSTRAINT \`FK_22113bc933266b8b87f291a9a72\` FOREIGN KEY (\`imageId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combos\` ADD CONSTRAINT \`FK_28648509d03f31d55c201f1130d\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` ADD CONSTRAINT \`FK_404d0ac5bd33b2bae5cbacace2b\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` ADD CONSTRAINT \`FK_6bbc7a32da0a87f37f093642244\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` ADD CONSTRAINT \`FK_9843df3b87b38c7424f513a8d7d\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` ADD CONSTRAINT \`FK_7a33905c073d9442989db7711e1\` FOREIGN KEY (\`receiptId\`) REFERENCES \`receipts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` ADD CONSTRAINT \`FK_7b3cc0b7a9798866a02e7a3a4f8\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` ADD CONSTRAINT \`FK_19b495041f74e73884b51dd8dad\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` ADD CONSTRAINT \`FK_95a869a52884aaeae719767a272\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`member-ranks\` ADD CONSTRAINT \`FK_47669af023975be175fa02d16f7\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_50976ab09a67603d04656554e2b\` FOREIGN KEY (\`personalInfoId\`) REFERENCES \`personal-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_23008f9303453ce01269707429d\` FOREIGN KEY (\`rankId\`) REFERENCES \`member-ranks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_b7837678f3d750698394a80f70a\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipts\` ADD CONSTRAINT \`FK_815e41f247aa1cd893731f1f534\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipts\` ADD CONSTRAINT \`FK_733f8febc9bbf9605f7c72b2d31\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipts\` ADD CONSTRAINT \`FK_2965a0ed54a06bcb4f6c8d1a32f\` FOREIGN KEY (\`spaceUnitId\`) REFERENCES \`space-units\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_f64f92f5eee5e9b7c9efabdfb07\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_eb4181527b71aa76bef4f2dc59f\` FOREIGN KEY (\`identityCardImage1Id\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_4cc978dbd3c0b4fe114bc1ab27a\` FOREIGN KEY (\`identityCardImage2Id\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_e2497a12faa9628c41bfdbaf98e\` FOREIGN KEY (\`personalInfoId\`) REFERENCES \`personal-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_8a50442b7b4f45142d2bc06af3c\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`configs\` ADD CONSTRAINT \`FK_f27ba1d5b1f169c9ce773bafe33\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-trackings\` ADD CONSTRAINT \`FK_2a1dee5d9475ab85d4b714fa274\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-trackings\` ADD CONSTRAINT \`FK_2dca5e1ec185841659b52245052\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` ADD CONSTRAINT \`FK_bb84f8edd17b8e275e6686021fc\` FOREIGN KEY (\`spaceUnitsId_1\`) REFERENCES \`space-units\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` ADD CONSTRAINT \`FK_2a236211c5f4925ec5e7b2bf945\` FOREIGN KEY (\`spaceUnitsId_2\`) REFERENCES \`space-units\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`receipt_products_promo_codes_promo-codes\` ADD CONSTRAINT \`FK_7e49ca7b593d039c39fe37e7605\` FOREIGN KEY (\`receiptProductsId\`) REFERENCES \`receiptProducts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`receipt_products_promo_codes_promo-codes\` ADD CONSTRAINT \`FK_bc195120a6e5ac1a8741cb25d8e\` FOREIGN KEY (\`promoCodesId\`) REFERENCES \`promo-codes\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`receipts_promo_codes_promo-codes\` ADD CONSTRAINT \`FK_8812c885c4168496babaf03a596\` FOREIGN KEY (\`receiptsId\`) REFERENCES \`receipts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`receipts_promo_codes_promo-codes\` ADD CONSTRAINT \`FK_ec4625350a66c8727f6d6dfef4f\` FOREIGN KEY (\`promoCodesId\`) REFERENCES \`promo-codes\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`receipts_promo_codes_promo-codes\` DROP FOREIGN KEY \`FK_ec4625350a66c8727f6d6dfef4f\``);
        await queryRunner.query(`ALTER TABLE \`receipts_promo_codes_promo-codes\` DROP FOREIGN KEY \`FK_8812c885c4168496babaf03a596\``);
        await queryRunner.query(`ALTER TABLE \`receipt_products_promo_codes_promo-codes\` DROP FOREIGN KEY \`FK_bc195120a6e5ac1a8741cb25d8e\``);
        await queryRunner.query(`ALTER TABLE \`receipt_products_promo_codes_promo-codes\` DROP FOREIGN KEY \`FK_7e49ca7b593d039c39fe37e7605\``);
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` DROP FOREIGN KEY \`FK_2a236211c5f4925ec5e7b2bf945\``);
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` DROP FOREIGN KEY \`FK_bb84f8edd17b8e275e6686021fc\``);
        await queryRunner.query(`ALTER TABLE \`combo-trackings\` DROP FOREIGN KEY \`FK_2dca5e1ec185841659b52245052\``);
        await queryRunner.query(`ALTER TABLE \`combo-trackings\` DROP FOREIGN KEY \`FK_2a1dee5d9475ab85d4b714fa274\``);
        await queryRunner.query(`ALTER TABLE \`configs\` DROP FOREIGN KEY \`FK_f27ba1d5b1f169c9ce773bafe33\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_8a50442b7b4f45142d2bc06af3c\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_e2497a12faa9628c41bfdbaf98e\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_4cc978dbd3c0b4fe114bc1ab27a\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_eb4181527b71aa76bef4f2dc59f\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_f64f92f5eee5e9b7c9efabdfb07\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`receipts\` DROP FOREIGN KEY \`FK_2965a0ed54a06bcb4f6c8d1a32f\``);
        await queryRunner.query(`ALTER TABLE \`receipts\` DROP FOREIGN KEY \`FK_733f8febc9bbf9605f7c72b2d31\``);
        await queryRunner.query(`ALTER TABLE \`receipts\` DROP FOREIGN KEY \`FK_815e41f247aa1cd893731f1f534\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_b7837678f3d750698394a80f70a\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_23008f9303453ce01269707429d\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_50976ab09a67603d04656554e2b\``);
        await queryRunner.query(`ALTER TABLE \`member-ranks\` DROP FOREIGN KEY \`FK_47669af023975be175fa02d16f7\``);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` DROP FOREIGN KEY \`FK_95a869a52884aaeae719767a272\``);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` DROP FOREIGN KEY \`FK_19b495041f74e73884b51dd8dad\``);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` DROP FOREIGN KEY \`FK_7b3cc0b7a9798866a02e7a3a4f8\``);
        await queryRunner.query(`ALTER TABLE \`receiptProducts\` DROP FOREIGN KEY \`FK_7a33905c073d9442989db7711e1\``);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` DROP FOREIGN KEY \`FK_9843df3b87b38c7424f513a8d7d\``);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` DROP FOREIGN KEY \`FK_6bbc7a32da0a87f37f093642244\``);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` DROP FOREIGN KEY \`FK_404d0ac5bd33b2bae5cbacace2b\``);
        await queryRunner.query(`ALTER TABLE \`combos\` DROP FOREIGN KEY \`FK_28648509d03f31d55c201f1130d\``);
        await queryRunner.query(`ALTER TABLE \`combos\` DROP FOREIGN KEY \`FK_22113bc933266b8b87f291a9a72\``);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` DROP FOREIGN KEY \`FK_d3a7e5e3ec3de49cdb1a156a667\``);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` DROP FOREIGN KEY \`FK_2841db6ff5a6d835770decb23d6\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_782da5e50e94b763eb63225d69d\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_e8c788030f2c88cbccf6965328c\``);
        await queryRunner.query(`ALTER TABLE \`spends\` DROP FOREIGN KEY \`FK_ce454cf10e9405c811a26b6e55d\``);
        await queryRunner.query(`ALTER TABLE \`stores\` DROP FOREIGN KEY \`FK_8268c3cb6bc33b77580220bcdc8\``);
        await queryRunner.query(`ALTER TABLE \`stores\` DROP FOREIGN KEY \`FK_f36d697e265ed99b80cae6984c9\``);
        await queryRunner.query(`ALTER TABLE \`spaces\` DROP FOREIGN KEY \`FK_86ece25c1dfe489bf748da779e6\``);
        await queryRunner.query(`ALTER TABLE \`space-units\` DROP FOREIGN KEY \`FK_ec10b62ba8854176bf8a386cd1a\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_533b61ed333a730035da8c1055d\``);
        await queryRunner.query(`ALTER TABLE \`personal-info\` DROP FOREIGN KEY \`FK_98ca4ec426318eb638694d4f542\``);
        await queryRunner.query(`ALTER TABLE \`photos\` DROP FOREIGN KEY \`FK_b8d4271e04660159c5f6fabfc9c\``);
        await queryRunner.query(`DROP INDEX \`IDX_ec4625350a66c8727f6d6dfef4\` ON \`receipts_promo_codes_promo-codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_8812c885c4168496babaf03a59\` ON \`receipts_promo_codes_promo-codes\``);
        await queryRunner.query(`DROP TABLE \`receipts_promo_codes_promo-codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_bc195120a6e5ac1a8741cb25d8\` ON \`receipt_products_promo_codes_promo-codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_7e49ca7b593d039c39fe37e760\` ON \`receipt_products_promo_codes_promo-codes\``);
        await queryRunner.query(`DROP TABLE \`receipt_products_promo_codes_promo-codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_2a236211c5f4925ec5e7b2bf94\` ON \`space-units_merged_unit_space-units\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb84f8edd17b8e275e6686021f\` ON \`space-units_merged_unit_space-units\``);
        await queryRunner.query(`DROP TABLE \`space-units_merged_unit_space-units\``);
        await queryRunner.query(`DROP TABLE \`combo-trackings\``);
        await queryRunner.query(`DROP TABLE \`configs\``);
        await queryRunner.query(`DROP INDEX \`REL_e2497a12faa9628c41bfdbaf98\` ON \`employee-info\``);
        await queryRunner.query(`DROP INDEX \`REL_4cc978dbd3c0b4fe114bc1ab27\` ON \`employee-info\``);
        await queryRunner.query(`DROP INDEX \`REL_eb4181527b71aa76bef4f2dc59\` ON \`employee-info\``);
        await queryRunner.query(`DROP TABLE \`employee-info\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`REL_2965a0ed54a06bcb4f6c8d1a32\` ON \`receipts\``);
        await queryRunner.query(`DROP TABLE \`receipts\``);
        await queryRunner.query(`DROP INDEX \`REL_50976ab09a67603d04656554e2\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP TABLE \`member-ranks\``);
        await queryRunner.query(`DROP TABLE \`receiptProducts\``);
        await queryRunner.query(`DROP TABLE \`promo-codes\``);
        await queryRunner.query(`DROP INDEX \`REL_22113bc933266b8b87f291a9a7\` ON \`combos\``);
        await queryRunner.query(`DROP TABLE \`combos\``);
        await queryRunner.query(`DROP TABLE \`combo-quantity\``);
        await queryRunner.query(`DROP INDEX \`REL_e8c788030f2c88cbccf6965328\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP TABLE \`spends\``);
        await queryRunner.query(`DROP INDEX \`REL_8268c3cb6bc33b77580220bcdc\` ON \`stores\``);
        await queryRunner.query(`DROP TABLE \`stores\``);
        await queryRunner.query(`DROP TABLE \`spaces\``);
        await queryRunner.query(`DROP TABLE \`space-units\``);
        await queryRunner.query(`DROP INDEX \`REL_533b61ed333a730035da8c1055\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_98ca4ec426318eb638694d4f54\` ON \`personal-info\``);
        await queryRunner.query(`DROP INDEX \`IDX_93b09314f05ed2653da12beabe\` ON \`personal-info\``);
        await queryRunner.query(`DROP TABLE \`personal-info\``);
        await queryRunner.query(`DROP TABLE \`photos\``);
    }

}
