import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1733189822481 implements MigrationInterface {
    name = 'Init1733189822481'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`photos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`mimeType\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`personal-info\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NOT NULL, \`firstName\` varchar(255) NULL, \`lastName\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`address\` varchar(255) NULL, \`dob\` date NULL, \`gender\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`profilePictureId\` int NULL, UNIQUE INDEX \`REL_98ca4ec426318eb638694d4f54\` (\`profilePictureId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`password\` varchar(255) NOT NULL, \`role\` int NOT NULL DEFAULT '1', \`notificationToken\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`personalInfoId\` int NULL, UNIQUE INDEX \`REL_533b61ed333a730035da8c1055\` (\`personalInfoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`space-units\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`status\` smallint NOT NULL DEFAULT '1', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`spaceId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`spaces\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stores\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` int NOT NULL DEFAULT '1', \`passCode\` varchar(255) NOT NULL, \`paymentDate\` int NOT NULL DEFAULT '1', \`hotline\` varchar(255) NULL, \`facebookUrl\` varchar(255) NULL, \`tiktokUrl\` varchar(255) NULL, \`youtubeUrl\` varchar(255) NULL, \`address\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`logoPictureId\` int NULL, UNIQUE INDEX \`REL_8268c3cb6bc33b77580220bcdc\` (\`logoPictureId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product-in-stock-daily\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal(7,1) NOT NULL DEFAULT '1.0', \`date\` date NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product-transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reason\` text NOT NULL, \`type\` int NOT NULL DEFAULT '0', \`quantity\` decimal(5,1) NOT NULL DEFAULT '1.0', \`date\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`productId\` int NULL, INDEX \`IDX_a1d1c58c93952704867d87026c\` (\`productId\`, \`quantity\`, \`date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`type\` tinyint NOT NULL DEFAULT '0', \`originalPrice\` decimal(11,2) NOT NULL DEFAULT '0.00', \`price\` decimal(11,2) NOT NULL DEFAULT '0.00', \`commissionRate\` decimal(11,2) NULL, \`commissionType\` int NULL, \`unit\` varchar(255) NOT NULL, \`category\` varchar(255) NOT NULL, \`duration\` int NULL, \`barcode\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`isStorable\` tinyint NOT NULL DEFAULT 1, \`isSaleable\` tinyint NOT NULL DEFAULT 1, \`toppingCategory\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`imageId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_e8c788030f2c88cbccf6965328\` (\`imageId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`combo-product-topping\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal(5,1) NOT NULL DEFAULT '1.0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`comboQuantityId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`combo-quantity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal(5,1) NOT NULL DEFAULT '1.0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`comboId\` int NULL, \`productUsedId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`combos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`originalPrice\` decimal(11,2) NOT NULL DEFAULT '0.00', \`price\` decimal(11,2) NOT NULL DEFAULT '0.00', \`commissionRate\` decimal(11,2) NULL, \`commissionType\` int NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`imageId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_22113bc933266b8b87f291a9a7\` (\`imageId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`package-product-quantity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal(5,1) NOT NULL DEFAULT '1.0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`packageId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`packages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`originalPrice\` decimal(11,2) NOT NULL DEFAULT '0.00', \`price\` decimal(11,2) NOT NULL DEFAULT '0.00', \`commissionRate\` decimal(11,2) NULL, \`commissionType\` int NULL, \`expiryTime\` int NULL, \`timesCanUse\` int NOT NULL DEFAULT '1', \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, \`imageId\` int NULL, UNIQUE INDEX \`REL_5baea1af19d8746fb213523e77\` (\`imageId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`member-ranks\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NULL, \`description\` varchar(255) NULL, \`condition\` tinyint NULL DEFAULT '0', \`requirement\` int NULL DEFAULT '0', \`dropRankInMonth\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`joinedDate\` date NULL, \`point\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`personalInfoId\` int NULL, \`rankId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_50976ab09a67603d04656554e2\` (\`personalInfoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receipt-product-topping\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal(5,1) NOT NULL DEFAULT '1.0', \`price\` decimal(11,2) NOT NULL DEFAULT '0.00', \`priceDiscounted\` decimal(11,2) NOT NULL DEFAULT '0.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`receiptProductId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receipt-products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal(5,1) NOT NULL DEFAULT '1.0', \`price\` decimal(11,2) NOT NULL DEFAULT '0.00', \`priceDiscounted\` decimal(11,2) NOT NULL DEFAULT '0.00', \`note\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`receiptId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, \`packageId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employee-info\` (\`id\` int NOT NULL AUTO_INCREMENT, \`isVerified\` tinyint NOT NULL DEFAULT 0, \`isActive\` tinyint NOT NULL DEFAULT 0, \`joinedDate\` date NULL, \`dayOffPerMonth\` int NULL DEFAULT '0', \`salary\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`identityCardImage1Id\` int NULL, \`identityCardImage2Id\` int NULL, \`personalInfoId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_eb4181527b71aa76bef4f2dc59\` (\`identityCardImage1Id\`), UNIQUE INDEX \`REL_4cc978dbd3c0b4fe114bc1ab27\` (\`identityCardImage2Id\`), UNIQUE INDEX \`REL_e2497a12faa9628c41bfdbaf98\` (\`personalInfoId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receipts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`subTotal\` decimal(11,2) NOT NULL DEFAULT '0.00', \`total\` decimal(11,2) NOT NULL DEFAULT '0.00', \`extraDiscount\` int NULL, \`pointRewarded\` int NULL, \`note\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, \`customerId\` int NULL, \`spaceUnitId\` int NULL, \`createdById\` int NULL, UNIQUE INDEX \`REL_2965a0ed54a06bcb4f6c8d1a32\` (\`spaceUnitId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`un-used-promo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`discountType\` tinyint NOT NULL DEFAULT '0', \`discountAmount\` decimal(5,2) NOT NULL DEFAULT '0.00', \`dueDate\` datetime NULL, \`used\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`customerId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, \`packageId\` int NULL, \`fromReceiptId\` int NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promo-codes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`description\` text NULL, \`quantity\` int NULL, \`numbersUsed\` int NULL DEFAULT '0', \`discountType\` int NULL, \`discountAmount\` decimal(11,2) NOT NULL DEFAULT '0.00', \`timeStart\` datetime NULL, \`timeEnd\` datetime NULL, \`itemQuantity\` int NULL, \`canUseWithOther\` tinyint NOT NULL DEFAULT 1, \`isPaused\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, \`packageId\` int NULL, UNIQUE INDEX \`IDX_cdf2a0ce026904f32a75095b26\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promo-campaign-bonus\` (\`id\` int NOT NULL AUTO_INCREMENT, \`discountType\` tinyint NOT NULL DEFAULT '0', \`discountAmount\` decimal(11,2) NOT NULL DEFAULT '0.00', \`maximumAmount\` decimal(11,2) NULL, \`quantity\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`promoCampaignsId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, \`packageId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promo-campaign-conditions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` decimal(11,2) NOT NULL DEFAULT '0.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`promoCampaignsId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, \`packageId\` int NULL, \`memberRankId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promo-campaigns\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NULL, \`description\` text NULL, \`timeStart\` datetime NULL, \`timeEnd\` datetime NULL, \`canUseWithOther\` tinyint NOT NULL DEFAULT 1, \`isPaused\` tinyint NOT NULL DEFAULT 0, \`timesUsed\` int NOT NULL DEFAULT '0', \`isCumulative\` tinyint NOT NULL DEFAULT 0, \`expiryDate\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`imageId\` int NULL, \`storeId\` int NULL, UNIQUE INDEX \`REL_2f3463d9a862184de536d20203\` (\`imageId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`receipt-promo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`discountType\` int NULL, \`discountAmount\` decimal(11,2) NOT NULL DEFAULT '0.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`receiptId\` int NULL, \`codeId\` int NULL, \`campaignId\` int NULL, \`receiptItemId\` int NULL, \`receiptToppingItemId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promo-code-on-hold\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`codeId\` int NULL, \`customerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`package-purchased\` (\`id\` int NOT NULL AUTO_INCREMENT, \`purchasedAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`customerId\` int NULL, \`packageId\` int NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`package-tracking\` (\`id\` int NOT NULL AUTO_INCREMENT, \`usedAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`packagePurchasedId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`package-tracking-product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantityUsed\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`packageTrackingId\` int NULL, \`productId\` int NULL, \`comboId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` varchar(255) NOT NULL, \`url\` varchar(255) NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`isSendMail\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`money-transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reason\` text NULL, \`amount\` decimal(14,2) NOT NULL DEFAULT '0.00', \`type\` tinyint NOT NULL, \`date\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`money-balance-daily\` (\`id\` int NOT NULL AUTO_INCREMENT, \`balance\` decimal(14,2) NOT NULL DEFAULT '0.00', \`date\` date NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employee-service-tracking\` (\`id\` int NOT NULL AUTO_INCREMENT, \`totalEarned\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`employeeId\` int NULL, \`receiptId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`configs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`value\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bookings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`timeArrive\` date NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`customerId\` int NULL, \`spaceUnitId\` int NULL, \`storeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`space-units_merged_unit_space-units\` (\`spaceUnitsId_1\` int NOT NULL, \`spaceUnitsId_2\` int NOT NULL, INDEX \`IDX_bb84f8edd17b8e275e6686021f\` (\`spaceUnitsId_1\`), INDEX \`IDX_2a236211c5f4925ec5e7b2bf94\` (\`spaceUnitsId_2\`), PRIMARY KEY (\`spaceUnitsId_1\`, \`spaceUnitsId_2\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`photos\` ADD CONSTRAINT \`FK_b8d4271e04660159c5f6fabfc9c\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`personal-info\` ADD CONSTRAINT \`FK_98ca4ec426318eb638694d4f542\` FOREIGN KEY (\`profilePictureId\`) REFERENCES \`photos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_533b61ed333a730035da8c1055d\` FOREIGN KEY (\`personalInfoId\`) REFERENCES \`personal-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`space-units\` ADD CONSTRAINT \`FK_ec10b62ba8854176bf8a386cd1a\` FOREIGN KEY (\`spaceId\`) REFERENCES \`spaces\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spaces\` ADD CONSTRAINT \`FK_86ece25c1dfe489bf748da779e6\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stores\` ADD CONSTRAINT \`FK_f36d697e265ed99b80cae6984c9\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stores\` ADD CONSTRAINT \`FK_8268c3cb6bc33b77580220bcdc8\` FOREIGN KEY (\`logoPictureId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product-in-stock-daily\` ADD CONSTRAINT \`FK_7fc0287219d732273df0a5e662f\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product-transactions\` ADD CONSTRAINT \`FK_01aa0429921a8c72a173e008738\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_e8c788030f2c88cbccf6965328c\` FOREIGN KEY (\`imageId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_782da5e50e94b763eb63225d69d\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-product-topping\` ADD CONSTRAINT \`FK_df7b0560d3ab9f978acf61f012b\` FOREIGN KEY (\`comboQuantityId\`) REFERENCES \`combo-quantity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-product-topping\` ADD CONSTRAINT \`FK_77e58017c4b04f5309380f80285\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` ADD CONSTRAINT \`FK_2841db6ff5a6d835770decb23d6\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` ADD CONSTRAINT \`FK_e38221ca38f2cbfd6b2abe0d26c\` FOREIGN KEY (\`productUsedId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combos\` ADD CONSTRAINT \`FK_22113bc933266b8b87f291a9a72\` FOREIGN KEY (\`imageId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`combos\` ADD CONSTRAINT \`FK_28648509d03f31d55c201f1130d\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-product-quantity\` ADD CONSTRAINT \`FK_77610edc7215b502b2c23d46c5c\` FOREIGN KEY (\`packageId\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-product-quantity\` ADD CONSTRAINT \`FK_71ba1ff0d3abcc3d86e5c4166f3\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-product-quantity\` ADD CONSTRAINT \`FK_c3d8d6685ca0b7ff4b2a4b36752\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`packages\` ADD CONSTRAINT \`FK_84d332f43a30502aef998713c1f\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`packages\` ADD CONSTRAINT \`FK_5baea1af19d8746fb213523e777\` FOREIGN KEY (\`imageId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`member-ranks\` ADD CONSTRAINT \`FK_47669af023975be175fa02d16f7\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_50976ab09a67603d04656554e2b\` FOREIGN KEY (\`personalInfoId\`) REFERENCES \`personal-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_23008f9303453ce01269707429d\` FOREIGN KEY (\`rankId\`) REFERENCES \`member-ranks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_b7837678f3d750698394a80f70a\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-product-topping\` ADD CONSTRAINT \`FK_ba5a65454e17c0c559360604b75\` FOREIGN KEY (\`receiptProductId\`) REFERENCES \`receipt-products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-product-topping\` ADD CONSTRAINT \`FK_385d4c3a0dfa828943e59e6f9e4\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` ADD CONSTRAINT \`FK_a0413924f4060581cc63492b7cc\` FOREIGN KEY (\`receiptId\`) REFERENCES \`receipts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` ADD CONSTRAINT \`FK_d290bc6b1fa19f16967d0aa1330\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` ADD CONSTRAINT \`FK_8d94d21a8f1cfbf165a6067981e\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` ADD CONSTRAINT \`FK_ade8d1bbd818ae6c1ef49fcfe78\` FOREIGN KEY (\`packageId\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_eb4181527b71aa76bef4f2dc59f\` FOREIGN KEY (\`identityCardImage1Id\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_4cc978dbd3c0b4fe114bc1ab27a\` FOREIGN KEY (\`identityCardImage2Id\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_e2497a12faa9628c41bfdbaf98e\` FOREIGN KEY (\`personalInfoId\`) REFERENCES \`personal-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-info\` ADD CONSTRAINT \`FK_8a50442b7b4f45142d2bc06af3c\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipts\` ADD CONSTRAINT \`FK_815e41f247aa1cd893731f1f534\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipts\` ADD CONSTRAINT \`FK_733f8febc9bbf9605f7c72b2d31\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipts\` ADD CONSTRAINT \`FK_2965a0ed54a06bcb4f6c8d1a32f\` FOREIGN KEY (\`spaceUnitId\`) REFERENCES \`space-units\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipts\` ADD CONSTRAINT \`FK_a8590867edda0c86986b022c090\` FOREIGN KEY (\`createdById\`) REFERENCES \`employee-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` ADD CONSTRAINT \`FK_28fde2744a9083fdebca4b9d54f\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` ADD CONSTRAINT \`FK_2f5ea54e4393f9ab60fd4fc0569\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` ADD CONSTRAINT \`FK_3ec4aaac2b2e0bd970eb698da90\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` ADD CONSTRAINT \`FK_503bf544a955a7ef13629796745\` FOREIGN KEY (\`packageId\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` ADD CONSTRAINT \`FK_77c91722a14d17faaeb7e809181\` FOREIGN KEY (\`fromReceiptId\`) REFERENCES \`receipts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` ADD CONSTRAINT \`FK_22048173140feb324f292a927b1\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` ADD CONSTRAINT \`FK_404d0ac5bd33b2bae5cbacace2b\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` ADD CONSTRAINT \`FK_6bbc7a32da0a87f37f093642244\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` ADD CONSTRAINT \`FK_9843df3b87b38c7424f513a8d7d\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` ADD CONSTRAINT \`FK_4a2e7e827d7881de2d34e2de6da\` FOREIGN KEY (\`packageId\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` ADD CONSTRAINT \`FK_4a3c6ccbdb545ec5777a4f6fab0\` FOREIGN KEY (\`promoCampaignsId\`) REFERENCES \`promo-campaigns\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` ADD CONSTRAINT \`FK_b42c990ffa1bc435cc14b3b9223\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` ADD CONSTRAINT \`FK_730e6eb611d089867c74c7263f0\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` ADD CONSTRAINT \`FK_e71e5b2f68df8a66ebd38a79cc0\` FOREIGN KEY (\`packageId\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` ADD CONSTRAINT \`FK_f3c0fc5f6c15d538ddec0e6b431\` FOREIGN KEY (\`promoCampaignsId\`) REFERENCES \`promo-campaigns\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` ADD CONSTRAINT \`FK_0d236a83aa54754d95ba16b390d\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` ADD CONSTRAINT \`FK_ca07d827bea9ccc6c376f4251b3\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` ADD CONSTRAINT \`FK_8c53d8606ff7e6475df98f46ac0\` FOREIGN KEY (\`packageId\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` ADD CONSTRAINT \`FK_049e51d425c45b54445bf9990f7\` FOREIGN KEY (\`memberRankId\`) REFERENCES \`member-ranks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaigns\` ADD CONSTRAINT \`FK_2f3463d9a862184de536d202031\` FOREIGN KEY (\`imageId\`) REFERENCES \`photos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-campaigns\` ADD CONSTRAINT \`FK_e6727e4fef7beea4cbe1a5a7ad6\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` ADD CONSTRAINT \`FK_aef9f541f946257ef4f2f995af1\` FOREIGN KEY (\`receiptId\`) REFERENCES \`receipts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` ADD CONSTRAINT \`FK_59636cdd11e65847ed6301eacbf\` FOREIGN KEY (\`codeId\`) REFERENCES \`promo-codes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` ADD CONSTRAINT \`FK_28ebbd5b4502a5140393e5a49b1\` FOREIGN KEY (\`campaignId\`) REFERENCES \`promo-campaigns\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` ADD CONSTRAINT \`FK_a20401b2673d8480f12c762b51e\` FOREIGN KEY (\`receiptItemId\`) REFERENCES \`receipt-products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` ADD CONSTRAINT \`FK_1d5a83c08fbee417ca37b94536e\` FOREIGN KEY (\`receiptToppingItemId\`) REFERENCES \`receipt-product-topping\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-code-on-hold\` ADD CONSTRAINT \`FK_87b86c4cc7aaef2f025e1c86994\` FOREIGN KEY (\`codeId\`) REFERENCES \`promo-codes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo-code-on-hold\` ADD CONSTRAINT \`FK_18564b5dbed80e40f4bb074f3ba\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-purchased\` ADD CONSTRAINT \`FK_087d7c57a42f5dafd88d785ed53\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-purchased\` ADD CONSTRAINT \`FK_00a11cb4b0296445fa113d92600\` FOREIGN KEY (\`packageId\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-purchased\` ADD CONSTRAINT \`FK_e112e7103b6210b099b13fe8144\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-tracking\` ADD CONSTRAINT \`FK_33831f2945faeb6dec1406f3157\` FOREIGN KEY (\`packagePurchasedId\`) REFERENCES \`package-purchased\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-tracking-product\` ADD CONSTRAINT \`FK_dd3a52f46100529c82574108397\` FOREIGN KEY (\`packageTrackingId\`) REFERENCES \`package-tracking\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-tracking-product\` ADD CONSTRAINT \`FK_5bcaa50f4077d2bc579709a698b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`package-tracking-product\` ADD CONSTRAINT \`FK_8ca5d7d97e75f46d7d0513c52bb\` FOREIGN KEY (\`comboId\`) REFERENCES \`combos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_f64f92f5eee5e9b7c9efabdfb07\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`money-transactions\` ADD CONSTRAINT \`FK_1373843b0eed570b38dbc0ad77c\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`money-balance-daily\` ADD CONSTRAINT \`FK_2fd4687bd3a128c11f809116e2d\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-service-tracking\` ADD CONSTRAINT \`FK_b66ec345dbb98cfa35872f344b7\` FOREIGN KEY (\`employeeId\`) REFERENCES \`employee-info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-service-tracking\` ADD CONSTRAINT \`FK_a43b0f547f645f23908e2335a3c\` FOREIGN KEY (\`receiptId\`) REFERENCES \`receipts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee-service-tracking\` ADD CONSTRAINT \`FK_2ed3871c0d7910a82be2737b0d9\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`configs\` ADD CONSTRAINT \`FK_f27ba1d5b1f169c9ce773bafe33\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_67b9cd20f987fc6dc70f7cd283f\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_f65e8cf3427c12114d3756b493a\` FOREIGN KEY (\`spaceUnitId\`) REFERENCES \`space-units\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_ab42398a4bd9c4e5a27d72916ab\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` ADD CONSTRAINT \`FK_bb84f8edd17b8e275e6686021fc\` FOREIGN KEY (\`spaceUnitsId_1\`) REFERENCES \`space-units\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` ADD CONSTRAINT \`FK_2a236211c5f4925ec5e7b2bf945\` FOREIGN KEY (\`spaceUnitsId_2\`) REFERENCES \`space-units\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` DROP FOREIGN KEY \`FK_2a236211c5f4925ec5e7b2bf945\``);
        await queryRunner.query(`ALTER TABLE \`space-units_merged_unit_space-units\` DROP FOREIGN KEY \`FK_bb84f8edd17b8e275e6686021fc\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_ab42398a4bd9c4e5a27d72916ab\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_f65e8cf3427c12114d3756b493a\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_67b9cd20f987fc6dc70f7cd283f\``);
        await queryRunner.query(`ALTER TABLE \`configs\` DROP FOREIGN KEY \`FK_f27ba1d5b1f169c9ce773bafe33\``);
        await queryRunner.query(`ALTER TABLE \`employee-service-tracking\` DROP FOREIGN KEY \`FK_2ed3871c0d7910a82be2737b0d9\``);
        await queryRunner.query(`ALTER TABLE \`employee-service-tracking\` DROP FOREIGN KEY \`FK_a43b0f547f645f23908e2335a3c\``);
        await queryRunner.query(`ALTER TABLE \`employee-service-tracking\` DROP FOREIGN KEY \`FK_b66ec345dbb98cfa35872f344b7\``);
        await queryRunner.query(`ALTER TABLE \`money-balance-daily\` DROP FOREIGN KEY \`FK_2fd4687bd3a128c11f809116e2d\``);
        await queryRunner.query(`ALTER TABLE \`money-transactions\` DROP FOREIGN KEY \`FK_1373843b0eed570b38dbc0ad77c\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_f64f92f5eee5e9b7c9efabdfb07\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`package-tracking-product\` DROP FOREIGN KEY \`FK_8ca5d7d97e75f46d7d0513c52bb\``);
        await queryRunner.query(`ALTER TABLE \`package-tracking-product\` DROP FOREIGN KEY \`FK_5bcaa50f4077d2bc579709a698b\``);
        await queryRunner.query(`ALTER TABLE \`package-tracking-product\` DROP FOREIGN KEY \`FK_dd3a52f46100529c82574108397\``);
        await queryRunner.query(`ALTER TABLE \`package-tracking\` DROP FOREIGN KEY \`FK_33831f2945faeb6dec1406f3157\``);
        await queryRunner.query(`ALTER TABLE \`package-purchased\` DROP FOREIGN KEY \`FK_e112e7103b6210b099b13fe8144\``);
        await queryRunner.query(`ALTER TABLE \`package-purchased\` DROP FOREIGN KEY \`FK_00a11cb4b0296445fa113d92600\``);
        await queryRunner.query(`ALTER TABLE \`package-purchased\` DROP FOREIGN KEY \`FK_087d7c57a42f5dafd88d785ed53\``);
        await queryRunner.query(`ALTER TABLE \`promo-code-on-hold\` DROP FOREIGN KEY \`FK_18564b5dbed80e40f4bb074f3ba\``);
        await queryRunner.query(`ALTER TABLE \`promo-code-on-hold\` DROP FOREIGN KEY \`FK_87b86c4cc7aaef2f025e1c86994\``);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` DROP FOREIGN KEY \`FK_1d5a83c08fbee417ca37b94536e\``);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` DROP FOREIGN KEY \`FK_a20401b2673d8480f12c762b51e\``);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` DROP FOREIGN KEY \`FK_28ebbd5b4502a5140393e5a49b1\``);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` DROP FOREIGN KEY \`FK_59636cdd11e65847ed6301eacbf\``);
        await queryRunner.query(`ALTER TABLE \`receipt-promo\` DROP FOREIGN KEY \`FK_aef9f541f946257ef4f2f995af1\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaigns\` DROP FOREIGN KEY \`FK_e6727e4fef7beea4cbe1a5a7ad6\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaigns\` DROP FOREIGN KEY \`FK_2f3463d9a862184de536d202031\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` DROP FOREIGN KEY \`FK_049e51d425c45b54445bf9990f7\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` DROP FOREIGN KEY \`FK_8c53d8606ff7e6475df98f46ac0\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` DROP FOREIGN KEY \`FK_ca07d827bea9ccc6c376f4251b3\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` DROP FOREIGN KEY \`FK_0d236a83aa54754d95ba16b390d\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-conditions\` DROP FOREIGN KEY \`FK_f3c0fc5f6c15d538ddec0e6b431\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` DROP FOREIGN KEY \`FK_e71e5b2f68df8a66ebd38a79cc0\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` DROP FOREIGN KEY \`FK_730e6eb611d089867c74c7263f0\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` DROP FOREIGN KEY \`FK_b42c990ffa1bc435cc14b3b9223\``);
        await queryRunner.query(`ALTER TABLE \`promo-campaign-bonus\` DROP FOREIGN KEY \`FK_4a3c6ccbdb545ec5777a4f6fab0\``);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` DROP FOREIGN KEY \`FK_4a2e7e827d7881de2d34e2de6da\``);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` DROP FOREIGN KEY \`FK_9843df3b87b38c7424f513a8d7d\``);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` DROP FOREIGN KEY \`FK_6bbc7a32da0a87f37f093642244\``);
        await queryRunner.query(`ALTER TABLE \`promo-codes\` DROP FOREIGN KEY \`FK_404d0ac5bd33b2bae5cbacace2b\``);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` DROP FOREIGN KEY \`FK_22048173140feb324f292a927b1\``);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` DROP FOREIGN KEY \`FK_77c91722a14d17faaeb7e809181\``);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` DROP FOREIGN KEY \`FK_503bf544a955a7ef13629796745\``);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` DROP FOREIGN KEY \`FK_3ec4aaac2b2e0bd970eb698da90\``);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` DROP FOREIGN KEY \`FK_2f5ea54e4393f9ab60fd4fc0569\``);
        await queryRunner.query(`ALTER TABLE \`un-used-promo\` DROP FOREIGN KEY \`FK_28fde2744a9083fdebca4b9d54f\``);
        await queryRunner.query(`ALTER TABLE \`receipts\` DROP FOREIGN KEY \`FK_a8590867edda0c86986b022c090\``);
        await queryRunner.query(`ALTER TABLE \`receipts\` DROP FOREIGN KEY \`FK_2965a0ed54a06bcb4f6c8d1a32f\``);
        await queryRunner.query(`ALTER TABLE \`receipts\` DROP FOREIGN KEY \`FK_733f8febc9bbf9605f7c72b2d31\``);
        await queryRunner.query(`ALTER TABLE \`receipts\` DROP FOREIGN KEY \`FK_815e41f247aa1cd893731f1f534\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_8a50442b7b4f45142d2bc06af3c\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_e2497a12faa9628c41bfdbaf98e\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_4cc978dbd3c0b4fe114bc1ab27a\``);
        await queryRunner.query(`ALTER TABLE \`employee-info\` DROP FOREIGN KEY \`FK_eb4181527b71aa76bef4f2dc59f\``);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` DROP FOREIGN KEY \`FK_ade8d1bbd818ae6c1ef49fcfe78\``);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` DROP FOREIGN KEY \`FK_8d94d21a8f1cfbf165a6067981e\``);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` DROP FOREIGN KEY \`FK_d290bc6b1fa19f16967d0aa1330\``);
        await queryRunner.query(`ALTER TABLE \`receipt-products\` DROP FOREIGN KEY \`FK_a0413924f4060581cc63492b7cc\``);
        await queryRunner.query(`ALTER TABLE \`receipt-product-topping\` DROP FOREIGN KEY \`FK_385d4c3a0dfa828943e59e6f9e4\``);
        await queryRunner.query(`ALTER TABLE \`receipt-product-topping\` DROP FOREIGN KEY \`FK_ba5a65454e17c0c559360604b75\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_b7837678f3d750698394a80f70a\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_23008f9303453ce01269707429d\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_50976ab09a67603d04656554e2b\``);
        await queryRunner.query(`ALTER TABLE \`member-ranks\` DROP FOREIGN KEY \`FK_47669af023975be175fa02d16f7\``);
        await queryRunner.query(`ALTER TABLE \`packages\` DROP FOREIGN KEY \`FK_5baea1af19d8746fb213523e777\``);
        await queryRunner.query(`ALTER TABLE \`packages\` DROP FOREIGN KEY \`FK_84d332f43a30502aef998713c1f\``);
        await queryRunner.query(`ALTER TABLE \`package-product-quantity\` DROP FOREIGN KEY \`FK_c3d8d6685ca0b7ff4b2a4b36752\``);
        await queryRunner.query(`ALTER TABLE \`package-product-quantity\` DROP FOREIGN KEY \`FK_71ba1ff0d3abcc3d86e5c4166f3\``);
        await queryRunner.query(`ALTER TABLE \`package-product-quantity\` DROP FOREIGN KEY \`FK_77610edc7215b502b2c23d46c5c\``);
        await queryRunner.query(`ALTER TABLE \`combos\` DROP FOREIGN KEY \`FK_28648509d03f31d55c201f1130d\``);
        await queryRunner.query(`ALTER TABLE \`combos\` DROP FOREIGN KEY \`FK_22113bc933266b8b87f291a9a72\``);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` DROP FOREIGN KEY \`FK_e38221ca38f2cbfd6b2abe0d26c\``);
        await queryRunner.query(`ALTER TABLE \`combo-quantity\` DROP FOREIGN KEY \`FK_2841db6ff5a6d835770decb23d6\``);
        await queryRunner.query(`ALTER TABLE \`combo-product-topping\` DROP FOREIGN KEY \`FK_77e58017c4b04f5309380f80285\``);
        await queryRunner.query(`ALTER TABLE \`combo-product-topping\` DROP FOREIGN KEY \`FK_df7b0560d3ab9f978acf61f012b\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_782da5e50e94b763eb63225d69d\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_e8c788030f2c88cbccf6965328c\``);
        await queryRunner.query(`ALTER TABLE \`product-transactions\` DROP FOREIGN KEY \`FK_01aa0429921a8c72a173e008738\``);
        await queryRunner.query(`ALTER TABLE \`product-in-stock-daily\` DROP FOREIGN KEY \`FK_7fc0287219d732273df0a5e662f\``);
        await queryRunner.query(`ALTER TABLE \`stores\` DROP FOREIGN KEY \`FK_8268c3cb6bc33b77580220bcdc8\``);
        await queryRunner.query(`ALTER TABLE \`stores\` DROP FOREIGN KEY \`FK_f36d697e265ed99b80cae6984c9\``);
        await queryRunner.query(`ALTER TABLE \`spaces\` DROP FOREIGN KEY \`FK_86ece25c1dfe489bf748da779e6\``);
        await queryRunner.query(`ALTER TABLE \`space-units\` DROP FOREIGN KEY \`FK_ec10b62ba8854176bf8a386cd1a\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_533b61ed333a730035da8c1055d\``);
        await queryRunner.query(`ALTER TABLE \`personal-info\` DROP FOREIGN KEY \`FK_98ca4ec426318eb638694d4f542\``);
        await queryRunner.query(`ALTER TABLE \`photos\` DROP FOREIGN KEY \`FK_b8d4271e04660159c5f6fabfc9c\``);
        await queryRunner.query(`DROP INDEX \`IDX_2a236211c5f4925ec5e7b2bf94\` ON \`space-units_merged_unit_space-units\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb84f8edd17b8e275e6686021f\` ON \`space-units_merged_unit_space-units\``);
        await queryRunner.query(`DROP TABLE \`space-units_merged_unit_space-units\``);
        await queryRunner.query(`DROP TABLE \`bookings\``);
        await queryRunner.query(`DROP TABLE \`configs\``);
        await queryRunner.query(`DROP TABLE \`employee-service-tracking\``);
        await queryRunner.query(`DROP TABLE \`money-balance-daily\``);
        await queryRunner.query(`DROP TABLE \`money-transactions\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`package-tracking-product\``);
        await queryRunner.query(`DROP TABLE \`package-tracking\``);
        await queryRunner.query(`DROP TABLE \`package-purchased\``);
        await queryRunner.query(`DROP TABLE \`promo-code-on-hold\``);
        await queryRunner.query(`DROP TABLE \`receipt-promo\``);
        await queryRunner.query(`DROP INDEX \`REL_2f3463d9a862184de536d20203\` ON \`promo-campaigns\``);
        await queryRunner.query(`DROP TABLE \`promo-campaigns\``);
        await queryRunner.query(`DROP TABLE \`promo-campaign-conditions\``);
        await queryRunner.query(`DROP TABLE \`promo-campaign-bonus\``);
        await queryRunner.query(`DROP INDEX \`IDX_cdf2a0ce026904f32a75095b26\` ON \`promo-codes\``);
        await queryRunner.query(`DROP TABLE \`promo-codes\``);
        await queryRunner.query(`DROP TABLE \`un-used-promo\``);
        await queryRunner.query(`DROP INDEX \`REL_2965a0ed54a06bcb4f6c8d1a32\` ON \`receipts\``);
        await queryRunner.query(`DROP TABLE \`receipts\``);
        await queryRunner.query(`DROP INDEX \`REL_e2497a12faa9628c41bfdbaf98\` ON \`employee-info\``);
        await queryRunner.query(`DROP INDEX \`REL_4cc978dbd3c0b4fe114bc1ab27\` ON \`employee-info\``);
        await queryRunner.query(`DROP INDEX \`REL_eb4181527b71aa76bef4f2dc59\` ON \`employee-info\``);
        await queryRunner.query(`DROP TABLE \`employee-info\``);
        await queryRunner.query(`DROP TABLE \`receipt-products\``);
        await queryRunner.query(`DROP TABLE \`receipt-product-topping\``);
        await queryRunner.query(`DROP INDEX \`REL_50976ab09a67603d04656554e2\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP TABLE \`member-ranks\``);
        await queryRunner.query(`DROP INDEX \`REL_5baea1af19d8746fb213523e77\` ON \`packages\``);
        await queryRunner.query(`DROP TABLE \`packages\``);
        await queryRunner.query(`DROP TABLE \`package-product-quantity\``);
        await queryRunner.query(`DROP INDEX \`REL_22113bc933266b8b87f291a9a7\` ON \`combos\``);
        await queryRunner.query(`DROP TABLE \`combos\``);
        await queryRunner.query(`DROP TABLE \`combo-quantity\``);
        await queryRunner.query(`DROP TABLE \`combo-product-topping\``);
        await queryRunner.query(`DROP INDEX \`REL_e8c788030f2c88cbccf6965328\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_a1d1c58c93952704867d87026c\` ON \`product-transactions\``);
        await queryRunner.query(`DROP TABLE \`product-transactions\``);
        await queryRunner.query(`DROP TABLE \`product-in-stock-daily\``);
        await queryRunner.query(`DROP INDEX \`REL_8268c3cb6bc33b77580220bcdc\` ON \`stores\``);
        await queryRunner.query(`DROP TABLE \`stores\``);
        await queryRunner.query(`DROP TABLE \`spaces\``);
        await queryRunner.query(`DROP TABLE \`space-units\``);
        await queryRunner.query(`DROP INDEX \`REL_533b61ed333a730035da8c1055\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_98ca4ec426318eb638694d4f54\` ON \`personal-info\``);
        await queryRunner.query(`DROP TABLE \`personal-info\``);
        await queryRunner.query(`DROP TABLE \`photos\``);
    }

}
